module.exports = {
  USER_ROLES: ['root', 'admin', 'hr', 'manager', 'center_manager', 'employee', 'supply_chain'],
  ASSESSMENT_STATUS: [
    'draft', 'in_progress', 'assessment_started',
    'pending_manager_review', 'approved', 'rejected',
    'hub_assigned', 'ready_for_pickup',
    'supply_chain_assigned', 'pickup_scheduled',
    'out_for_pickup', 'arrived_at_customer',
    'otp_verified', 'customer_verified',
    'deal_confirmed', 'payment_completed',
    'collected', 'in_transit', 'arrived_at_hub',
    'delivered', 'received', 'ready_for_processing',
    'customer_unavailable', 'otp_failed', 'customer_cancelled',
    'requires_manager_review', 'transport_delayed',
    'delivery_exception', 'completed', 'cancelled',
  ],
  PRODUCT_CONDITIONS: ['excellent', 'good', 'fair', 'poor', 'damaged'],
  CLASSIFICATIONS: ['reusable', 'repairable', 'recyclable', 'scrap'],
  FACILITY_TYPES: ['collection_center', 'preprocessing_unit', 'dismantling', 'recovery'],
  FACILITY_STATUS: ['active', 'inactive', 'under_maintenance'],
  FORECAST_DATA_TYPES: ['historical_collection', 'population', 'product_sales', 'import_export', 'revenue', 'operational_costs'],
  FORECAST_DATA_STATUS: ['uploaded', 'validated', 'imported', 'failed'],
  RECOMMENDATION_TYPES: ['new_center', 'new_unit', 'expansion', 'logistics_optimization'],
  RECOMMENDATION_FEASIBILITY: ['high', 'medium', 'low'],
  RECOMMENDATION_STATUS: ['pending', 'approved', 'implemented', 'rejected'],
  REGION_TYPES: ['state', 'city'],
  // Product category groups as defined in the GreenEra spec
  PRODUCT_CATEGORIES: {
    IT: { label: 'IT – Information Technology', items: ['Laptop', 'Desktop', 'Server', 'Mobile Phone', 'Tablet', 'Monitor', 'Printer', 'Router', 'Keyboard', 'Mouse', 'Others'] },
    CE: { label: 'CE – Consumer Electronics', items: ['Television', 'Air Conditioner', 'Refrigerator', 'Washing Machine', 'Fan', 'Microwave Oven', 'Music System', 'Others'] },
    LS: { label: 'LS – Large/Small Household Appliances', items: ['Rice Cooker', 'Induction Stove', 'Mixer Grinder', 'Vacuum Cleaner', 'Iron Box', 'Water Purifier', 'Geyser', 'Others'] },
    EE: { label: 'EE – Electrical & Electronic Tools', items: ['Drilling Machine', 'Welding Machine', 'Power Tools', 'Testing Equipment', 'Others'] },
    TLS: { label: 'TLS – Toys, Leisure & Sports Equipment', items: ['Gaming Console', 'Drone', 'Electronic Toys', 'Treadmill', 'Exercise Equipment', 'Others'] },
    LI: { label: 'LI – Lighting Instruments', items: ['LED Bulb', 'Tube Light', 'Emergency Light', 'Street Light', 'Decorative Lighting', 'Others'] },
    MD: { label: 'MD – Medical Devices', items: ['Blood Pressure Monitor', 'Thermometer', 'Pulse Oximeter', 'Nebulizer', 'Glucose Meter', 'ECG Device', 'Others'] },
  },
  // Dynamic questionnaire templates keyed by product name
  PRODUCT_QUESTIONS: {
    Laptop: [
      { id: 'qPowerOn', label: 'Does the device power on?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'intermittent', label: 'Intermittent' }, { value: 'no', label: 'No' }] },
      { id: 'qBatteryHealth', label: 'Battery Health?', type: 'select', options: [{ value: 'good', label: 'Good (80%+)' }, { value: 'fair', label: 'Fair (50-80%)' }, { value: 'poor', label: 'Poor (<50%)' }, { value: 'dead', label: 'Dead/Not Working' }] },
      { id: 'qRam', label: 'RAM Size?', type: 'select', options: [{ value: '2gb', label: '2 GB' }, { value: '4gb', label: '4 GB' }, { value: '8gb', label: '8 GB' }, { value: '16gb', label: '16 GB' }, { value: '32gb', label: '32 GB+' }] },
      { id: 'qProcessor', label: 'Processor Type?', type: 'select', options: [{ value: 'i3', label: 'Intel i3' }, { value: 'i5', label: 'Intel i5' }, { value: 'i7', label: 'Intel i7' }, { value: 'i9', label: 'Intel i9' }, { value: 'ryzen3', label: 'AMD Ryzen 3' }, { value: 'ryzen5', label: 'AMD Ryzen 5' }, { value: 'ryzen7', label: 'AMD Ryzen 7' }, { value: 'm1', label: 'Apple M1' }, { value: 'm2', label: 'Apple M2' }, { value: 'other', label: 'Other' }] },
      { id: 'qStorage', label: 'Storage Type & Size?', type: 'select', options: [{ value: 'hdd_250', label: 'HDD <250GB' }, { value: 'hdd_500', label: 'HDD 500GB' }, { value: 'hdd_1tb', label: 'HDD 1TB+' }, { value: 'ssd_128', label: 'SSD 128GB' }, { value: 'ssd_256', label: 'SSD 256GB' }, { value: 'ssd_512', label: 'SSD 512GB+' }] },
      { id: 'qScreenCondition', label: 'Screen Condition?', type: 'select', options: [{ value: 'perfect', label: 'Perfect - No issues' }, { value: 'minor_scratches', label: 'Minor scratches' }, { value: 'dead_pixels', label: 'Dead pixels' }, { value: 'cracked', label: 'Cracked' }, { value: 'broken', label: 'Broken/No Display' }] },
      { id: 'qKeyboardCondition', label: 'Keyboard Condition?', type: 'select', options: [{ value: 'perfect', label: 'Perfect' }, { value: 'some_keys', label: 'Some keys not working' }, { value: 'damaged', label: 'Damaged/Missing keys' }] },
    ],
    Desktop: [
      { id: 'qPowerOn', label: 'Does the system power on?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'intermittent', label: 'Intermittent' }, { value: 'no', label: 'No' }] },
      { id: 'qRam', label: 'RAM Size?', type: 'select', options: [{ value: '2gb', label: '2 GB' }, { value: '4gb', label: '4 GB' }, { value: '8gb', label: '8 GB' }, { value: '16gb', label: '16 GB' }, { value: '32gb', label: '32 GB+' }] },
      { id: 'qProcessor', label: 'Processor Type?', type: 'select', options: [{ value: 'i3', label: 'Intel i3' }, { value: 'i5', label: 'Intel i5' }, { value: 'i7', label: 'Intel i7' }, { value: 'i9', label: 'Intel i9' }, { value: 'ryzen3', label: 'AMD Ryzen 3' }, { value: 'ryzen5', label: 'AMD Ryzen 5' }, { value: 'ryzen7', label: 'AMD Ryzen 7' }, { value: 'other', label: 'Other' }] },
      { id: 'qStorage', label: 'Storage?', type: 'select', options: [{ value: 'hdd', label: 'HDD' }, { value: 'ssd', label: 'SSD' }, { value: 'nvme', label: 'NVMe' }, { value: 'none', label: 'No Storage' }] },
      { id: 'qGpu', label: 'Dedicated GPU?', type: 'select', options: [{ value: 'none', label: 'None (Integrated)' }, { value: 'entry', label: 'Entry Level' }, { value: 'mid', label: 'Mid Range' }, { value: 'high', label: 'High End' }] },
    ],
    Server: [
      { id: 'qPowerOn', label: 'Does the server power on?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'intermittent', label: 'Intermittent' }, { value: 'no', label: 'No' }] },
      { id: 'qRackMount', label: 'Form Factor?', type: 'select', options: [{ value: 'rack', label: 'Rack Mount' }, { value: 'tower', label: 'Tower' }, { value: 'blade', label: 'Blade' }] },
      { id: 'qRam', label: 'RAM Size?', type: 'select', options: [{ value: '16gb', label: '16 GB' }, { value: '32gb', label: '32 GB' }, { value: '64gb', label: '64 GB' }, { value: '128gb', label: '128 GB+' }] },
      { id: 'qStorageType', label: 'Storage Configuration?', type: 'select', options: [{ value: 'sas', label: 'SAS' }, { value: 'sata', label: 'SATA' }, { value: 'nvme', label: 'NVMe' }, { value: 'mixed', label: 'Mixed' }] },
      { id: 'qRaidSupport', label: 'RAID Support?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }] },
    ],
    'Mobile Phone': [
      { id: 'qPowerOn', label: 'Does the phone power on?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'intermittent', label: 'Intermittent' }, { value: 'no', label: 'No' }] },
      { id: 'qDisplayCondition', label: 'Display Condition?', type: 'select', options: [{ value: 'perfect', label: 'Perfect' }, { value: 'scratched', label: 'Scratched' }, { value: 'cracked', label: 'Cracked Glass' }, { value: 'dead_pixels', label: 'Dead Pixels' }, { value: 'no_display', label: 'No Display' }] },
      { id: 'qBatteryHealth', label: 'Battery Health?', type: 'select', options: [{ value: 'good', label: 'Good (>80%)' }, { value: 'fair', label: 'Fair (50-80%)' }, { value: 'poor', label: 'Poor (<50%)' }, { value: 'swollen', label: 'Swollen/Damaged' }] },
      { id: 'qCameraWorking', label: 'Camera Working?', type: 'select', options: [{ value: 'both', label: 'Both Front & Back' }, { value: 'rear_only', label: 'Rear Only' }, { value: 'front_only', label: 'Front Only' }, { value: 'none', label: 'Not Working' }] },
      { id: 'qTouchScreen', label: 'Touch Screen Working?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'partial', label: 'Partial' }, { value: 'no', label: 'No' }] },
      { id: 'qImeiAvailable', label: 'IMEI Available?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No/Blank' }] },
    ],
    Tablet: [
      { id: 'qPowerOn', label: 'Does the tablet power on?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'intermittent', label: 'Intermittent' }, { value: 'no', label: 'No' }] },
      { id: 'qDisplayCondition', label: 'Display Condition?', type: 'select', options: [{ value: 'perfect', label: 'Perfect' }, { value: 'scratched', label: 'Scratched' }, { value: 'cracked', label: 'Cracked' }, { value: 'dead_pixels', label: 'Dead Pixels' }] },
      { id: 'qBatteryHealth', label: 'Battery Health?', type: 'select', options: [{ value: 'good', label: 'Good' }, { value: 'fair', label: 'Fair' }, { value: 'poor', label: 'Poor' }, { value: 'swollen', label: 'Swollen' }] },
      { id: 'qTouchScreen', label: 'Touch Screen Working?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'partial', label: 'Partial' }, { value: 'no', label: 'No' }] },
    ],
    Monitor: [
      { id: 'qPowerOn', label: 'Does the monitor power on?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'intermittent', label: 'Intermittent' }, { value: 'no', label: 'No' }] },
      { id: 'qScreenCondition', label: 'Screen Condition?', type: 'select', options: [{ value: 'perfect', label: 'Perfect' }, { value: 'scratched', label: 'Scratched' }, { value: 'dead_pixels', label: 'Dead Pixels' }, { value: 'cracked', label: 'Cracked' }, { value: 'lines', label: 'Lines/Artifacts' }] },
      { id: 'qPortsWorking', label: 'Ports Functional?', type: 'select', options: [{ value: 'all', label: 'All Working' }, { value: 'partial', label: 'Partial' }, { value: 'none', label: 'None' }] },
      { id: 'qStandIncluded', label: 'Stand Included?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }] },
    ],
    Printer: [
      { id: 'qPowerOn', label: 'Does the printer power on?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }] },
      { id: 'qPrintTest', label: 'Does it print?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'poor', label: 'Poor Quality' }, { value: 'no', label: 'No' }] },
      { id: 'qInkType', label: 'Ink/Toner Type?', type: 'select', options: [{ value: 'inkjet', label: 'Inkjet' }, { value: 'laser', label: 'Laser' }, { value: 'dotmatrix', label: 'Dot Matrix' }, { value: 'thermal', label: 'Thermal' }] },
      { id: 'qConnectivity', label: 'Connectivity?', type: 'select', options: [{ value: 'usb', label: 'USB Only' }, { value: 'wifi', label: 'WiFi' }, { value: 'ethernet', label: 'Ethernet' }, { value: 'multiple', label: 'Multiple' }] },
    ],
    Router: [
      { id: 'qPowerOn', label: 'Does the router power on?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'intermittent', label: 'Intermittent' }, { value: 'no', label: 'No' }] },
      { id: 'qWifiStandard', label: 'WiFi Standard?', type: 'select', options: [{ value: 'wifi4', label: 'WiFi 4 (n)' }, { value: 'wifi5', label: 'WiFi 5 (ac)' }, { value: 'wifi6', label: 'WiFi 6 (ax)' }, { value: 'wifi6e', label: 'WiFi 6E' }, { value: 'wifi7', label: 'WiFi 7' }] },
      { id: 'qPortsWorking', label: 'Ethernet Ports Working?', type: 'select', options: [{ value: 'all', label: 'All Working' }, { value: 'partial', label: 'Some Working' }, { value: 'none', label: 'None' }] },
    ],
    Television: [
      { id: 'qPowerOn', label: 'Does the TV power on?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'intermittent', label: 'Intermittent' }, { value: 'no', label: 'No' }] },
      { id: 'qScreenCondition', label: 'Screen Condition?', type: 'select', options: [{ value: 'perfect', label: 'Perfect' }, { value: 'scratched', label: 'Scratched' }, { value: 'dead_pixels', label: 'Dead Pixels' }, { value: 'lines', label: 'Lines/Bands' }, { value: 'cracked', label: 'Cracked/Broken' }] },
      { id: 'qDisplayType', label: 'Display Type?', type: 'select', options: [{ value: 'led', label: 'LED' }, { value: 'lcd', label: 'LCD' }, { value: 'oled', label: 'OLED' }, { value: 'plasma', label: 'Plasma' }, { value: 'crt', label: 'CRT' }] },
      { id: 'qRemotePresent', label: 'Remote Control Present?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }] },
      { id: 'qSmartTv', label: 'Smart TV?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }] },
    ],
    'Air Conditioner': [
      { id: 'qPowerOn', label: 'Does the AC power on?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'intermittent', label: 'Intermittent' }, { value: 'no', label: 'No' }] },
      { id: 'qCoolingWorking', label: 'Cooling Working?', type: 'select', options: [{ value: 'yes', label: 'Yes - Cools well' }, { value: 'weak', label: 'Weak cooling' }, { value: 'no', label: 'No cooling' }] },
      { id: 'qCompressorWorking', label: 'Compressor Working?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'noisy', label: 'Noisy' }, { value: 'no', label: 'Not Working' }] },
      { id: 'qGasLeak', label: 'Gas Leak Suspected?', type: 'select', options: [{ value: 'no', label: 'No' }, { value: 'possible', label: 'Possible' }, { value: 'yes', label: 'Yes' }] },
      { id: 'qCapacity', label: 'Capacity (Tons)?', type: 'select', options: [{ value: '1', label: '1 Ton' }, { value: '1.5', label: '1.5 Ton' }, { value: '2', label: '2 Ton' }, { value: '2.5', label: '2.5 Ton' }, { value: '3', label: '3 Ton+' }] },
      { id: 'qType', label: 'AC Type?', type: 'select', options: [{ value: 'split', label: 'Split' }, { value: 'window', label: 'Window' }, { value: 'portable', label: 'Portable' }, { value: 'cassette', label: 'Cassette' }] },
    ],
    Refrigerator: [
      { id: 'qPowerOn', label: 'Does the refrigerator power on?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'intermittent', label: 'Intermittent' }, { value: 'no', label: 'No' }] },
      { id: 'qCoolingWorking', label: 'Cooling Working?', type: 'select', options: [{ value: 'both', label: 'Both Fridge & Freezer' }, { value: 'fridge_only', label: 'Fridge Only' }, { value: 'weak', label: 'Weak Cooling' }, { value: 'no', label: 'Not Cooling' }] },
      { id: 'qCompressorWorking', label: 'Compressor Working?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'noisy', label: 'Noisy' }, { value: 'no', label: 'Not Working' }] },
      { id: 'qGasLeak', label: 'Gas Leak?', type: 'select', options: [{ value: 'no', label: 'No' }, { value: 'possible', label: 'Possible' }, { value: 'yes', label: 'Yes' }] },
      { id: 'qDoorCondition', label: 'Door Condition?', type: 'select', options: [{ value: 'good', label: 'Good' }, { value: 'damaged', label: 'Damaged Seal' }, { value: 'broken', label: 'Broken Hinge' }] },
    ],
    'Washing Machine': [
      { id: 'qPowerOn', label: 'Does the machine power on?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'intermittent', label: 'Intermittent' }, { value: 'no', label: 'No' }] },
      { id: 'qSpinWorking', label: 'Spin Cycle Working?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'noisy', label: 'Noisy/Vibrating' }, { value: 'no', label: 'Not Working' }] },
      { id: 'qDrumCondition', label: 'Drum Condition?', type: 'select', options: [{ value: 'good', label: 'Good' }, { value: 'rusty', label: 'Rusty' }, { value: 'damaged', label: 'Damaged' }] },
      { id: 'qWaterLeak', label: 'Water Leak?', type: 'select', options: [{ value: 'no', label: 'No' }, { value: 'minor', label: 'Minor Leak' }, { value: 'major', label: 'Major Leak' }] },
      { id: 'qMachineType', label: 'Machine Type?', type: 'select', options: [{ value: 'front', label: 'Front Load' }, { value: 'top', label: 'Top Load' }, { value: 'semi', label: 'Semi-Automatic' }] },
    ],
    Fan: [
      { id: 'qPowerOn', label: 'Does the fan work?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'intermittent', label: 'Intermittent' }, { value: 'no', label: 'No' }] },
      { id: 'qSpeedControl', label: 'Speed Control Working?', type: 'select', options: [{ value: 'all', label: 'All Speeds' }, { value: 'partial', label: 'Some Speeds' }, { value: 'no', label: 'Not Working' }] },
      { id: 'qNoiseLevel', label: 'Noise Level?', type: 'select', options: [{ value: 'quiet', label: 'Quiet' }, { value: 'moderate', label: 'Moderate' }, { value: 'noisy', label: 'Noisy' }] },
      { id: 'qFanType', label: 'Fan Type?', type: 'select', options: [{ value: 'ceiling', label: 'Ceiling' }, { value: 'table', label: 'Table/Pedestal' }, { value: 'wall', label: 'Wall Mount' }, { value: 'exhaust', label: 'Exhaust' }] },
    ],
    'Microwave Oven': [
      { id: 'qPowerOn', label: 'Does the microwave power on?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }] },
      { id: 'qHeatingWorking', label: 'Heating Working?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'weak', label: 'Weak' }, { value: 'no', label: 'No' }] },
      { id: 'qTurntableWorking', label: 'Turntable Working?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }] },
      { id: 'qDoorCondition', label: 'Door Seal Condition?', type: 'select', options: [{ value: 'good', label: 'Good' }, { value: 'damaged', label: 'Damaged' }] },
    ],
    'Music System': [
      { id: 'qPowerOn', label: 'Does the system power on?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'intermittent', label: 'Intermittent' }, { value: 'no', label: 'No' }] },
      { id: 'qSoundOutput', label: 'Sound Output?', type: 'select', options: [{ value: 'all', label: 'All Channels Working' }, { value: 'partial', label: 'Partial' }, { value: 'distorted', label: 'Distorted' }, { value: 'no', label: 'No Sound' }] },
      { id: 'qConnectivity', label: 'Connectivity?', type: 'select', options: [{ value: 'all', label: 'All Working' }, { value: 'partial', label: 'Partial' }, { value: 'none', label: 'None' }] },
    ],
    'Rice Cooker': [
      { id: 'qPowerOn', label: 'Does the rice cooker power on?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }] },
      { id: 'qHeatingWorking', label: 'Heating Working?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'weak', label: 'Weak' }, { value: 'no', label: 'No' }] },
      { id: 'qInnerPotCondition', label: 'Inner Pot Condition?', type: 'select', options: [{ value: 'good', label: 'Good' }, { value: 'scratched', label: 'Scratched (Non-stick damaged)' }, { value: 'damaged', label: 'Damaged' }] },
    ],
    'Induction Stove': [
      { id: 'qPowerOn', label: 'Does the stove power on?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }] },
      { id: 'qHeatingWorking', label: 'Heating Working?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'intermittent', label: 'Intermittent' }, { value: 'no', label: 'No' }] },
      { id: 'qGlassTopCondition', label: 'Glass Top Condition?', type: 'select', options: [{ value: 'good', label: 'Good' }, { value: 'cracked', label: 'Cracked' }, { value: 'broken', label: 'Broken' }] },
    ],
    'Mixer Grinder': [
      { id: 'qPowerOn', label: 'Does the mixer power on?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }] },
      { id: 'qMotorWorking', label: 'Motor Working?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'slow', label: 'Slow' }, { value: 'noisy', label: 'Noisy' }, { value: 'no', label: 'Not Working' }] },
      { id: 'qJarsCondition', label: 'Jars Condition?', type: 'select', options: [{ value: 'all', label: 'All Jars Good' }, { value: 'some', label: 'Some Damaged' }, { value: 'none', label: 'All Damaged' }] },
    ],
    'Vacuum Cleaner': [
      { id: 'qPowerOn', label: 'Does the vacuum power on?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'intermittent', label: 'Intermittent' }, { value: 'no', label: 'No' }] },
      { id: 'qSuctionPower', label: 'Suction Power?', type: 'select', options: [{ value: 'strong', label: 'Strong' }, { value: 'weak', label: 'Weak' }, { value: 'none', label: 'No Suction' }] },
      { id: 'qFilterCondition', label: 'Filter Condition?', type: 'select', options: [{ value: 'good', label: 'Good' }, { value: 'needs_replacement', label: 'Needs Replacement' }, { value: 'missing', label: 'Missing' }] },
    ],
    'Iron Box': [
      { id: 'qPowerOn', label: 'Does the iron heat up?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'intermittent', label: 'Intermittent' }, { value: 'no', label: 'No' }] },
      { id: 'qSoleplateCondition', label: 'Soleplate Condition?', type: 'select', options: [{ value: 'good', label: 'Good' }, { value: 'scratched', label: 'Scratched' }, { value: 'damaged', label: 'Damaged' }] },
      { id: 'qCordCondition', label: 'Power Cord Condition?', type: 'select', options: [{ value: 'good', label: 'Good' }, { value: 'frayed', label: 'Frayed' }, { value: 'damaged', label: 'Damaged' }] },
    ],
    'Water Purifier': [
      { id: 'qPowerOn', label: 'Does the purifier power on?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }] },
      { id: 'qWaterFlow', label: 'Water Flow?', type: 'select', options: [{ value: 'normal', label: 'Normal' }, { value: 'slow', label: 'Slow' }, { value: 'no', label: 'No Flow' }] },
      { id: 'qPurificationType', label: 'Purification Type?', type: 'select', options: [{ value: 'ro', label: 'RO' }, { value: 'uv', label: 'UV' }, { value: 'uf', label: 'UF' }, { value: 'gravity', label: 'Gravity Based' }] },
    ],
    Geyser: [
      { id: 'qPowerOn', label: 'Does the geyser power on?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }] },
      { id: 'qHeatingWorking', label: 'Water Heating?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'slow', label: 'Slow' }, { value: 'no', label: 'No' }] },
      { id: 'qWaterLeak', label: 'Water Leak?', type: 'select', options: [{ value: 'no', label: 'No' }, { value: 'minor', label: 'Minor' }, { value: 'major', label: 'Major' }] },
    ],
    'Drilling Machine': [
      { id: 'qPowerOn', label: 'Does the drill power on?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'intermittent', label: 'Intermittent' }, { value: 'no', label: 'No' }] },
      { id: 'qChuckCondition', label: 'Chuck Condition?', type: 'select', options: [{ value: 'good', label: 'Good' }, { value: 'worn', label: 'Worn' }, { value: 'damaged', label: 'Damaged' }] },
      { id: 'qSpeedControl', label: 'Speed Control Working?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }] },
    ],
    'Welding Machine': [
      { id: 'qPowerOn', label: 'Does the welder power on?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }] },
      { id: 'qWeldingOutput', label: 'Welding Output?', type: 'select', options: [{ value: 'good', label: 'Good' }, { value: 'weak', label: 'Weak' }, { value: 'no', label: 'No Output' }] },
      { id: 'qCableCondition', label: 'Cables Condition?', type: 'select', options: [{ value: 'good', label: 'Good' }, { value: 'damaged', label: 'Damaged' }] },
    ],
    'Power Tools': [
      { id: 'qPowerOn', label: 'Does the tool power on?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'intermittent', label: 'Intermittent' }, { value: 'no', label: 'No' }] },
      { id: 'qMotorWorking', label: 'Motor Working?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'noisy', label: 'Noisy' }, { value: 'no', label: 'Not Working' }] },
      { id: 'qAccessoriesIncluded', label: 'Accessories Included?', type: 'select', options: [{ value: 'all', label: 'All' }, { value: 'partial', label: 'Partial' }, { value: 'none', label: 'None' }] },
    ],
    'Testing Equipment': [
      { id: 'qPowerOn', label: 'Does the equipment power on?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }] },
      { id: 'qCalibration', label: 'Calibration Status?', type: 'select', options: [{ value: 'calibrated', label: 'Calibrated' }, { value: 'unknown', label: 'Unknown' }, { value: 'needs', label: 'Needs Calibration' }] },
      { id: 'qProbesIncluded', label: 'Probes/Accessories Included?', type: 'select', options: [{ value: 'all', label: 'All' }, { value: 'partial', label: 'Partial' }, { value: 'none', label: 'None' }] },
    ],
    'Gaming Console': [
      { id: 'qPowerOn', label: 'Does the console power on?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'intermittent', label: 'Intermittent' }, { value: 'no', label: 'No' }] },
      { id: 'qDiscDrive', label: 'Disc Drive Working?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'noisy', label: 'Noisy' }, { value: 'no', label: 'Not Working' }, { value: 'digital', label: 'Digital Only (No Drive)' }] },
      { id: 'qControllerCondition', label: 'Controller(s) Condition?', type: 'select', options: [{ value: 'good', label: 'Good' }, { value: 'worn', label: 'Worn' }, { value: 'damaged', label: 'Damaged' }, { value: 'none', label: 'No Controller' }] },
      { id: 'qConsoleType', label: 'Console Type?', type: 'select', options: [{ value: 'ps4', label: 'PlayStation 4' }, { value: 'ps5', label: 'PlayStation 5' }, { value: 'xbox_one', label: 'Xbox One' }, { value: 'xbox_series', label: 'Xbox Series S/X' }, { value: 'switch', label: 'Nintendo Switch' }, { value: 'other', label: 'Other' }] },
    ],
    Drone: [
      { id: 'qPowerOn', label: 'Does the drone power on?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }] },
      { id: 'qFlightCapability', label: 'Flight Capability?', type: 'select', options: [{ value: 'flies', label: 'Flies Normally' }, { value: 'limited', label: 'Limited' }, { value: 'no', label: 'Cannot Fly' }] },
      { id: 'qCameraWorking', label: 'Camera Working?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }, { value: 'no_camera', label: 'No Camera' }] },
      { id: 'qBatteryHealth', label: 'Battery Health?', type: 'select', options: [{ value: 'good', label: 'Good' }, { value: 'fair', label: 'Fair' }, { value: 'poor', label: 'Poor' }, { value: 'swollen', label: 'Swollen' }] },
    ],
    'Electronic Toys': [
      { id: 'qPowerOn', label: 'Does the toy power on?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'intermittent', label: 'Intermittent' }, { value: 'no', label: 'No' }] },
      { id: 'qFunctionality', label: 'All Functions Working?', type: 'select', options: [{ value: 'all', label: 'All' }, { value: 'partial', label: 'Partial' }, { value: 'none', label: 'None' }] },
      { id: 'qDamage', label: 'Physical Damage?', type: 'select', options: [{ value: 'none', label: 'None' }, { value: 'minor', label: 'Minor' }, { value: 'major', label: 'Major' }] },
    ],
    Treadmill: [
      { id: 'qPowerOn', label: 'Does the treadmill power on?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }] },
      { id: 'qMotorWorking', label: 'Motor Working?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'noisy', label: 'Noisy' }, { value: 'no', label: 'Not Working' }] },
      { id: 'qBeltCondition', label: 'Belt Condition?', type: 'select', options: [{ value: 'good', label: 'Good' }, { value: 'worn', label: 'Worn' }, { value: 'damaged', label: 'Damaged' }] },
      { id: 'qDisplayWorking', label: 'Display/Console Working?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'partial', label: 'Partial' }, { value: 'no', label: 'No' }] },
    ],
    'Exercise Equipment': [
      { id: 'qPowerOn', label: 'Does the equipment power on (if electronic)?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }, { value: 'na', label: 'N/A (Non-electronic)' }] },
      { id: 'qStructuralCondition', label: 'Structural Condition?', type: 'select', options: [{ value: 'good', label: 'Good' }, { value: 'worn', label: 'Worn' }, { value: 'damaged', label: 'Damaged' }] },
      { id: 'qMovingParts', label: 'Moving Parts Condition?', type: 'select', options: [{ value: 'smooth', label: 'Smooth' }, { value: 'stiff', label: 'Stiff' }, { value: 'damaged', label: 'Damaged' }] },
    ],
    'LED Bulb': [
      { id: 'qWorking', label: 'Does the bulb light up?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'flickers', label: 'Flickers' }, { value: 'no', label: 'No' }] },
      { id: 'qWattage', label: 'Wattage?', type: 'select', options: [{ value: '5w', label: '5W' }, { value: '9w', label: '9W' }, { value: '12w', label: '12W' }, { value: '15w', label: '15W' }, { value: '20w', label: '20W+' }] },
    ],
    'Tube Light': [
      { id: 'qWorking', label: 'Does the tube light work?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'flickers', label: 'Flickers' }, { value: 'no', label: 'No' }] },
      { id: 'qType', label: 'Type?', type: 'select', options: [{ value: 'led', label: 'LED' }, { value: 'fluorescent', label: 'Fluorescent' }] },
    ],
    'Emergency Light': [
      { id: 'qPowerOn', label: 'Does it power on?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }] },
      { id: 'qBatteryWorking', label: 'Battery Working?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'weak', label: 'Weak' }, { value: 'no', label: 'No' }] },
    ],
    'Street Light': [
      { id: 'qWorking', label: 'Does the street light work?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'flickers', label: 'Flickers' }, { value: 'no', label: 'No' }] },
      { id: 'qType', label: 'Type?', type: 'select', options: [{ value: 'led', label: 'LED' }, { value: 'solar', label: 'Solar' }, { value: 'halogen', label: 'Halogen' }] },
    ],
    'Decorative Lighting': [
      { id: 'qWorking', label: 'Does the lighting work?', type: 'select', options: [{ value: 'all', label: 'All LEDs Working' }, { value: 'partial', label: 'Some Not Working' }, { value: 'no', label: 'Not Working' }] },
      { id: 'qType', label: 'Type?', type: 'select', options: [{ value: 'string', label: 'String Lights' }, { value: 'rope', label: 'Rope Lights' }, { value: 'festival', label: 'Festival Lights' }, { value: 'other', label: 'Other' }] },
    ],
    'Blood Pressure Monitor': [
      { id: 'qPowerOn', label: 'Does the monitor power on?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }] },
      { id: 'qDisplayWorking', label: 'Display Working?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'dim', label: 'Dim/Faint' }, { value: 'no', label: 'No Display' }] },
      { id: 'qCuffCondition', label: 'Cuff Condition?', type: 'select', options: [{ value: 'good', label: 'Good' }, { value: 'damaged', label: 'Damaged' }, { value: 'missing', label: 'Missing' }] },
    ],
    Thermometer: [
      { id: 'qWorking', label: 'Does the thermometer work?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'intermittent', label: 'Intermittent' }, { value: 'no', label: 'No' }] },
      { id: 'qType', label: 'Type?', type: 'select', options: [{ value: 'digital', label: 'Digital' }, { value: 'infrared', label: 'Infrared' }, { value: 'mercury', label: 'Mercury (Old)' }] },
    ],
    'Pulse Oximeter': [
      { id: 'qPowerOn', label: 'Does the oximeter power on?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }] },
      { id: 'qDisplayWorking', label: 'Display Working?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'dim', label: 'Dim' }, { value: 'no', label: 'No' }] },
    ],
    Nebulizer: [
      { id: 'qPowerOn', label: 'Does the nebulizer power on?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }] },
      { id: 'qMistOutput', label: 'Mist Output?', type: 'select', options: [{ value: 'good', label: 'Good' }, { value: 'weak', label: 'Weak' }, { value: 'no', label: 'No Mist' }] },
    ],
    'Glucose Meter': [
      { id: 'qPowerOn', label: 'Does the meter power on?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }] },
      { id: 'qDisplayWorking', label: 'Display Working?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'dim', label: 'Dim' }, { value: 'no', label: 'No' }] },
      { id: 'qTestStrips', label: 'Test Strips Included?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }] },
    ],
    'ECG Device': [
      { id: 'qPowerOn', label: 'Does the device power on?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }] },
      { id: 'qDisplayWorking', label: 'Display Working?', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'partial', label: 'Partial' }, { value: 'no', label: 'No' }] },
      { id: 'qLeadsCondition', label: 'Leads/Cables Condition?', type: 'select', options: [{ value: 'good', label: 'Good' }, { value: 'damaged', label: 'Damaged' }, { value: 'missing', label: 'Missing' }] },
    ],
  },
};
